// <auto-generated />
namespace MyLinkhay.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Linkhay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Linkhay));
        
        string IMigrationMetadata.Id
        {
            get { return "201501311014299_Linkhay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
